#!/bin/bash -l

#List various flags needed for this job

# job name
#$-N exp_recog_test-image

# time limit
#$-l h_rt=48:00:00

#join error and output streams
#$-j y

# specify the number of cpus
#$-pe omp 1

# specify the number of gpus
#$-l gpus=1

# specify GPU capability
#$-l gpu_c=3.5

#Load modules

module load cuda/8.0
module load cudnn/5.1
module load python/2.7.13
module load tensorflow/r1.0_python-2.7.13
module load keras/2.0.6


#Run python script
python exp_recog_test-image.py
