'''
	Author: Davide Lucchi - 12/7/2017
'''
import sys,re
import numpy as np
import os.path
from os import listdir
from os.path import isfile, join

# Read the files with the output AUs generated by open face and parse them in 
# order to save the occurences, intensities for each image
mypath = 'fer2013_AU'
onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]

# initialize output arrays
final_intens = np.empty([17])
final_occur = np.empty([18])


labels = np.load('labels.npy')

indexes = ['0']

print('parsing files')
for filename in onlyfiles:

    if os.path.exists('{}/{}'.format(mypath,filename)):
    
        #parse the filename to get the image number
        s = filename[filename.find('images')+len('images'):filename.find('_det_0')]
        indexes.append(s)
        
        
        data = open('{}/{}'.format(mypath,filename),'r').read()

        features = data[data.find("npoints")+len("npoints: 68\n{\n"):data.find("}\npose")]
        features = re.split('[\n]',features)
        features = features[:len(features)-1]
        
        intens = data[data.find("intensities")+len("intensities: 17 {"):data.find('}\nau occ')]
        occur =  data[data.find("occurences:")+len("occurences: 18 {"):]

        intens = re.split('[ \n]',intens)
        intens = intens[1:len(intens)-1]
        intens = intens[1::2]
        intens = list(map(float, intens))

        occur = re.split('[ \n]',occur)
        occur = occur[1:len(occur)-2]
        occur = occur[1::2]
        occur = list(map(float, occur))

        
        intens = np.array(intens)
        occur = np.array(occur)
        
        final_intens = np.vstack((final_intens,intens))
        final_occur = np.vstack((final_occur,occur))
        
    else:
        continue
        
final_intens = np.delete(final_intens,0,0)
final_occur = np.delete(final_occur,0,0)

print(final_intens)
print(final_intens.shape)

print(final_occur)
print(final_occur.shape)

del indexes[0]
indexes = list(map(int,indexes))

# get the labels for the set images for which we have AUs
labels = labels[indexes]

print(labels)
print(labels.shape)

np.save('intens_fer.npy',final_intens)
np.save('occur_fer.npy',final_occur)
np.save('fer_labels.npy',labels)

